apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
      - name: my-python-app-container
        image: my_python_openvino_app_with_ssh # Replace with your image name
        ports:
        - containerPort: 22  # SSH port
        - containerPort: 5000  # Application port
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]  # Required for starting SSH service
        volumeMounts:
        - name: dri
          mountPath: /dev/dri
      volumes:
      - name: dri
        hostPath:
          path: /dev/dri
apiVersion: v1
kind: Service
metadata:
  name: my-python-app-service
spec:
  type: NodePort
  ports:
    targetPort: 22
    nodePort: 32222  # Choose a port in the range 30000-32767
    protocol: TCP
    name: ssh
    targetPort: 5000
    nodePort: 30050  # Choose a port in the range 30000-32767
    protocol: TCP
    name: app-port
  selector:
    app: my-python-app
