apiVersion: apps/v1
kind: Deployment
metadata:
  name: explore-mfg-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explore-demo
  template:
    metadata:
      labels:
        app: explore-demo
    spec:
      hostNetwork: true
      containers:
      - name: explore-demo
        image: kmikholap/explore-mfg-demo:v2
