apiVersion: v1
kind: Namespace
metadata:
  name: openvino-dev-ssh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvino-deployment
  namespace: openvino-dev-ssh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openvino-runtime-ssh
  template:
    metadata:
      labels:
        app: openvino-runtime-ssh
    spec:
      containers:
      - name: openvino-runtime-ssh-container
        image: kmikholap/u-openvino-ssh-v3:latest
        limits:
            intel.com/gpu: 1
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]  # Required for starting SSH service
        volumeMounts:
        - name: dri
          mountPath: /dev/dri
        - name: devdir
          mountPath: /dev
        - name: sysdir
          mountPath: /sys
      volumes:
      - name: sysdir
        hostPath:
          path: /sys
          type: Directory
      - name: devdir
        hostPath:
          path: /dev
          type: Directory
      - name: dri
        hostPath:
          path: /dev/dri
---
apiVersion: v1
kind: Service
metadata:
  name: openvino-runtime-ssh-service
  namespace: openvino-dev-ssh
spec:
  type: NodePort
  ports:
  - port: 2222
    targetPort: 22
    nodePort: 30222  # Choose a port in the range 30000-32767
    protocol: TCP
    name: ssh
  selector:
    app: openvino-runtime-ssh
